<?php

namespace Proxies\__CG__\BackOfficeBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Package extends \BackOfficeBundle\Entity\Package implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'BackOfficeBundle\\Entity\\Package' . "\0" . 'id', 'name', 'accommodation', 'spots', 'options', 'flight', 'packages', 'datePrices', 'infos', 'insurances', 'providers', 'products', 'surfpriceId', 'production', 'adultNb', 'childNb', 'babyNb', 'dayNb', 'dateUpdate', 'boat', 'divingCenters', 'fees', 'price', 'includedOptions', 'destinationName');
        }

        return array('__isInitialized__', '' . "\0" . 'BackOfficeBundle\\Entity\\Package' . "\0" . 'id', 'name', 'accommodation', 'spots', 'options', 'flight', 'packages', 'datePrices', 'infos', 'insurances', 'providers', 'products', 'surfpriceId', 'production', 'adultNb', 'childNb', 'babyNb', 'dayNb', 'dateUpdate', 'boat', 'divingCenters', 'fees', 'price', 'includedOptions', 'destinationName');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Package $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setDestinationName($destinationName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDestinationName', array($destinationName));

        return parent::setDestinationName($destinationName);
    }

    /**
     * {@inheritDoc}
     */
    public function getDestinationName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDestinationName', array());

        return parent::getDestinationName();
    }

    /**
     * {@inheritDoc}
     */
    public function setAccommodation($accommodation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccommodation', array($accommodation));

        return parent::setAccommodation($accommodation);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccommodation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccommodation', array());

        return parent::getAccommodation();
    }

    /**
     * {@inheritDoc}
     */
    public function setSpots($spots)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSpots', array($spots));

        return parent::setSpots($spots);
    }

    /**
     * {@inheritDoc}
     */
    public function getSpots()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpots', array());

        return parent::getSpots();
    }

    /**
     * {@inheritDoc}
     */
    public function setProducts($products)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProducts', array($products));

        return parent::setProducts($products);
    }

    /**
     * {@inheritDoc}
     */
    public function getProducts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProducts', array());

        return parent::getProducts();
    }

    /**
     * {@inheritDoc}
     */
    public function setOptions($options)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOptions', array($options));

        return parent::setOptions($options);
    }

    /**
     * {@inheritDoc}
     */
    public function getOptions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOptions', array());

        return parent::getOptions();
    }

    /**
     * {@inheritDoc}
     */
    public function setFlight($flight)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFlight', array($flight));

        return parent::setFlight($flight);
    }

    /**
     * {@inheritDoc}
     */
    public function getFlight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFlight', array());

        return parent::getFlight();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatePrices($datePrices)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatePrices', array($datePrices));

        return parent::setDatePrices($datePrices);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatePrices()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatePrices', array());

        return parent::getDatePrices();
    }

    /**
     * {@inheritDoc}
     */
    public function setInfos($infos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInfos', array($infos));

        return parent::setInfos($infos);
    }

    /**
     * {@inheritDoc}
     */
    public function getInfos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInfos', array());

        return parent::getInfos();
    }

    /**
     * {@inheritDoc}
     */
    public function setInsurances($insurances)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInsurances', array($insurances));

        return parent::setInsurances($insurances);
    }

    /**
     * {@inheritDoc}
     */
    public function getInsurances()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInsurances', array());

        return parent::getInsurances();
    }

    /**
     * {@inheritDoc}
     */
    public function setProviders($providers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProviders', array($providers));

        return parent::setProviders($providers);
    }

    /**
     * {@inheritDoc}
     */
    public function getProviders()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProviders', array());

        return parent::getProviders();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrestations($prestations)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrestations', array($prestations));

        return parent::setPrestations($prestations);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrestations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrestations', array());

        return parent::getPrestations();
    }

    /**
     * {@inheritDoc}
     */
    public function setSurfpriceId($surfpriceId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSurfpriceId', array($surfpriceId));

        return parent::setSurfpriceId($surfpriceId);
    }

    /**
     * {@inheritDoc}
     */
    public function getSurfpriceId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSurfpriceId', array());

        return parent::getSurfpriceId();
    }

    /**
     * {@inheritDoc}
     */
    public function setProduction($production)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProduction', array($production));

        return parent::setProduction($production);
    }

    /**
     * {@inheritDoc}
     */
    public function getProduction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProduction', array());

        return parent::getProduction();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdultNb($adultNb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdultNb', array($adultNb));

        return parent::setAdultNb($adultNb);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdultNb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdultNb', array());

        return parent::getAdultNb();
    }

    /**
     * {@inheritDoc}
     */
    public function setChildNb($childNb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChildNb', array($childNb));

        return parent::setChildNb($childNb);
    }

    /**
     * {@inheritDoc}
     */
    public function getChildNb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChildNb', array());

        return parent::getChildNb();
    }

    /**
     * {@inheritDoc}
     */
    public function setBabyNb($babyNb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBabyNb', array($babyNb));

        return parent::setBabyNb($babyNb);
    }

    /**
     * {@inheritDoc}
     */
    public function getBabyNb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBabyNb', array());

        return parent::getBabyNb();
    }

    /**
     * {@inheritDoc}
     */
    public function setDayNb($dayNb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDayNb', array($dayNb));

        return parent::setDayNb($dayNb);
    }

    /**
     * {@inheritDoc}
     */
    public function getDayNb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDayNb', array());

        return parent::getDayNb();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateUpdate($dateUpdate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateUpdate', array($dateUpdate));

        return parent::setDateUpdate($dateUpdate);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateUpdate', array());

        return parent::getDateUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function setBoat($boat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBoat', array($boat));

        return parent::setBoat($boat);
    }

    /**
     * {@inheritDoc}
     */
    public function getBoat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBoat', array());

        return parent::getBoat();
    }

    /**
     * {@inheritDoc}
     */
    public function setDivingCenters($divingCenters)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDivingCenters', array($divingCenters));

        return parent::setDivingCenters($divingCenters);
    }

    /**
     * {@inheritDoc}
     */
    public function getDivingCenters()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDivingCenters', array());

        return parent::getDivingCenters();
    }

    /**
     * {@inheritDoc}
     */
    public function setFees($fees)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFees', array($fees));

        return parent::setFees($fees);
    }

    /**
     * {@inheritDoc}
     */
    public function getFees()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFees', array());

        return parent::getFees();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice($price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', array($price));

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', array());

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function getIncludedOptions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIncludedOptions', array());

        return parent::getIncludedOptions();
    }

    /**
     * {@inheritDoc}
     */
    public function setIncludedOptions($includedOptions = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIncludedOptions', array($includedOptions));

        return parent::setIncludedOptions($includedOptions);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
