<?php

namespace BackOfficeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FourthRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FourthRepository extends EntityRepository {
}
