<?php

namespace BackOfficeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SecondRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecondRepository extends EntityRepository {
}
