<?php

namespace BackOfficeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SlideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlideRepository extends EntityRepository {
	public function findBySlider($id)
	{
	
		$rawSql = "SELECT slide_id FROM slider_slide WHERE slider_id = '.$id.'";
	
		$stmt = $this->getEntityManager()->getConnection()->prepare($rawSql);
		$stmt->execute([]);
	
		return $stmt->fetchAll();
	}
}
